'use client';

import { createFileRoute } from "../router";
import { Mail, MapPin, MessageCircle } from "lucide-react";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Textarea } from "../components/ui/textarea";
import { PageHeading } from "../components/store/page-heading";
export const Route = createFileRoute("/contacto")({ head: () => ({ meta: [{ title: "Contacto — LUME." }, { name: "description", content: "Fale com a equipa da LUME. por mensagem, WhatsApp ou email." }, { property: "og:title", content: "Contacto — LUME." }, { property: "og:description", content: "Fale com a equipa da LUME. por mensagem, WhatsApp ou email." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ContactPage });
function ContactPage() { const sendMessage = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const subject = encodeURIComponent(`Contacto de ${String(data.get("name") ?? "cliente")}`); const body = encodeURIComponent(`${String(data.get("message") ?? "")}\n\nEmail: ${String(data.get("email") ?? "")}`); window.location.href = `mailto:ola@nomedaloja.co.mz?subject=${subject}&body=${body}`; }; return <><PageHeading eyebrow="Fale connosco" title="Contacto" description="Envie uma mensagem ou escolha um dos canais diretos da loja."/><section className="mx-auto grid max-w-6xl gap-10 px-5 py-10 sm:px-6 md:grid-cols-[1fr_.8fr]"><form className="grid gap-4" onSubmit={sendMessage}><label className="grid gap-2 text-sm font-semibold">Nome<Input name="name" required placeholder="O seu nome"/></label><label className="grid gap-2 text-sm font-semibold">Email<Input name="email" type="email" required placeholder="nome@exemplo.com"/></label><label className="grid gap-2 text-sm font-semibold">Mensagem<Textarea name="message" required className="min-h-32" placeholder="Como podemos ajudar?"/></label><Button size="lg" type="submit">Enviar mensagem</Button></form><div className="grid content-start gap-3"><ContactItem href="https://wa.me/258840000000" icon={<MessageCircle/>} title="WhatsApp" detail="+258 84 000 0000"/><ContactItem href="mailto:ola@nomedaloja.co.mz" icon={<Mail/>} title="Email" detail="ola@nomedaloja.co.mz"/><ContactItem href="https://maps.google.com/?q=Maputo%2C+Moçambique" icon={<MapPin/>} title="Loja" detail="Maputo, Moçambique"/><p className="mt-2 text-xs leading-5 text-muted-foreground">Os dados de contacto apresentados são demonstrativos e devem ser substituídos pelos dados oficiais da loja.</p></div></section></>; }
function ContactItem({ href, icon, title, detail }: { href: string; icon: React.ReactNode; title: string; detail: string }) { return <a href={href} target="_blank" rel="noreferrer" className="flex items-center gap-3 border-b border-border py-4 transition-colors hover:text-muted-foreground"><span className="grid size-10 place-items-center rounded-full bg-muted [&_svg]:size-4">{icon}</span><div><p className="text-sm font-semibold">{title}</p><p className="text-sm text-muted-foreground">{detail}</p></div></a>; }
