import type { SettingDef } from "@/theme-editor/editor/contracts/types";

const B = "basic" as const;
const A = "advanced" as const;

export const container: SettingDef[] = [
  {
    key: "colorScheme",
    label: "Esquema de cor",
    control: "colorScheme",
    tier: B,
    group: "appearance",
    default: "light",
    requires: "colorSchemes",
  },
  {
    key: "align",
    label: "Alinhamento",
    control: "align",
    tier: B,
    group: "layout",
    responsive: true,
    default: "left",
  },
  {
    key: "contentWidth",
    label: "Largura do conteúdo",
    control: "segmented",
    tier: B,
    group: "layout",
    responsive: true,
    default: "normal",
    options: [
      { value: "narrow", label: "Estreita" },
      { value: "normal", label: "Normal" },
      { value: "wide", label: "Larga" },
      { value: "full", label: "Total" },
    ],
  },
  {
    key: "spacing",
    label: "Espaçamento vertical",
    control: "sizePreset",
    tier: B,
    group: "spacing",
    responsive: true,
    default: 64,
    min: 0,
    max: 160,
    unit: "px",
    options: [
      { value: 32, label: "Compacto" },
      { value: 64, label: "Normal" },
      { value: 96, label: "Espaçoso" },
    ],
  },
  {
    key: "padding",
    label: "Padding lateral",
    control: "slider",
    tier: A,
    group: "spacing",
    responsive: true,
    default: 24,
    min: 0,
    max: 120,
    unit: "px",
  },
  {
    key: "gap",
    label: "Espaço entre itens",
    control: "slider",
    tier: A,
    group: "spacing",
    responsive: true,
    default: 24,
    min: 0,
    max: 64,
    unit: "px",
  },
  {
    key: "background",
    label: "Fundo",
    control: "color",
    tier: A,
    group: "appearance",
    default: "",
  },
  {
    key: "radius",
    label: "Arredondamento",
    control: "radius",
    tier: A,
    group: "appearance",
    default: 0,
    min: 0,
    max: 48,
    unit: "px",
  },
  {
    key: "shadow",
    label: "Sombra",
    control: "shadow",
    tier: A,
    group: "appearance",
    default: "none",
  },
  {
    key: "minHeight",
    label: "Altura mínima",
    control: "slider",
    tier: A,
    group: "layout",
    responsive: true,
    default: 0,
    min: 0,
    max: 900,
    unit: "px",
  },
  {
    key: "visibility",
    label: "Mostrar em",
    control: "visibilityByDevice",
    tier: A,
    group: "responsive",
    default: { desktop: true, tablet: true, mobile: true },
  },
  {
    key: "animation",
    label: "Animação ao aparecer",
    control: "animationPreset",
    tier: A,
    group: "behavior",
    requires: "animations",
    default: "none",
    options: [
      { value: "none", label: "Nenhuma" },
      { value: "fade", label: "Aparecer" },
      { value: "up", label: "Subir" },
    ],
  },
  {
    key: "anchorId",
    label: "ID da âncora",
    help: "Para links internos (letras, números e hífen).",
    control: "text",
    tier: A,
    group: "advanced",
    default: "",
    maxLength: 40,
  },
];

export const heading: SettingDef[] = [
  { key: "text", label: "Texto", control: "text", tier: B, group: "content", default: "", maxLength: 120 },
  { key: "show", label: "Mostrar", control: "toggle", tier: B, group: "content", default: true },
  {
    key: "align",
    label: "Alinhamento",
    control: "align",
    tier: B,
    group: "layout",
    responsive: true,
    default: "inherit",
  },
  {
    key: "color",
    label: "Cor",
    control: "color",
    tier: B,
    group: "appearance",
    default: "token:text",
    assist: { contrastWith: "background" },
  },
  {
    key: "size",
    label: "Tamanho",
    control: "sizePreset",
    tier: B,
    group: "typography",
    responsive: true,
    default: 36,
    min: 12,
    max: 120,
    unit: "px",
    options: [
      { value: 22, label: "S" },
      { value: 28, label: "M" },
      { value: 36, label: "L" },
      { value: 48, label: "XL" },
    ],
  },
  {
    key: "htmlTag",
    label: "Etiqueta semântica (SEO)",
    control: "select",
    tier: A,
    group: "advanced",
    default: "h2",
    options: ["h1", "h2", "h3", "h4", "h5", "h6", "p"].map((v) => ({ value: v, label: v.toUpperCase() })),
  },
  {
    key: "font",
    label: "Fonte",
    control: "font",
    tier: A,
    group: "typography",
    default: "inherit",
  },
  {
    key: "weight",
    label: "Peso",
    control: "fontWeight",
    tier: A,
    group: "typography",
    default: 600,
  },
  {
    key: "lineHeight",
    label: "Altura de linha",
    control: "slider",
    tier: A,
    group: "typography",
    default: 1.15,
    min: 0.9,
    max: 2.2,
    step: 0.05,
  },
  {
    key: "letterSpacing",
    label: "Espaçamento de letras",
    control: "slider",
    tier: A,
    group: "typography",
    default: 0,
    min: -0.05,
    max: 0.3,
    step: 0.01,
    unit: "em",
  },
  {
    key: "transform",
    label: "Transformação",
    control: "segmented",
    tier: A,
    group: "typography",
    default: "none",
    options: [
      { value: "none", label: "Normal" },
      { value: "uppercase", label: "MAIÚSC." },
      { value: "capitalize", label: "Capitalizar" },
    ],
  },
  {
    key: "maxLines",
    label: "Limite de linhas",
    control: "select",
    tier: A,
    group: "layout",
    default: 0,
    options: [
      { value: 0, label: "Sem limite" },
      { value: 1, label: "1" },
      { value: 2, label: "2" },
      { value: 3, label: "3" },
      { value: 4, label: "4" },
    ],
  },
  {
    key: "marginBottom",
    label: "Espaço por baixo",
    control: "slider",
    tier: A,
    group: "spacing",
    responsive: true,
    default: 12,
    min: 0,
    max: 96,
    unit: "px",
  },
  {
    key: "opacity",
    label: "Opacidade",
    control: "slider",
    tier: A,
    group: "appearance",
    default: 100,
    min: 0,
    max: 100,
    unit: "%",
  },
  {
    key: "visibility",
    label: "Mostrar em",
    control: "visibilityByDevice",
    tier: A,
    group: "responsive",
    default: { desktop: true, tablet: true, mobile: true },
  },
];

export const text: SettingDef[] = heading
  .filter((s) => !["htmlTag"].includes(s.key))
  .map((s) => {
    if (s.key === "text")
      return { ...s, control: "textarea" as const, maxLength: 600, default: "" };
    if (s.key === "size")
      return {
        ...s,
        default: 16,
        min: 11,
        max: 28,
        options: [
          { value: 14, label: "S" },
          { value: 16, label: "M" },
          { value: 20, label: "L" },
        ],
      };
    if (s.key === "weight") return { ...s, default: 400 };
    if (s.key === "lineHeight") return { ...s, default: 1.6 };
    if (s.key === "color") return { ...s, default: "token:text" };
    return s;
  });

export const image: SettingDef[] = [
  { key: "image", label: "Imagem", control: "image", tier: B, group: "content", default: null },
  {
    key: "alt",
    label: "Descrição da imagem",
    help: "Para acessibilidade e SEO.",
    control: "text",
    tier: B,
    group: "content",
    default: "",
    maxLength: 120,
  },
  { key: "show", label: "Mostrar", control: "toggle", tier: B, group: "content", default: true },
  {
    key: "aspectRatio",
    label: "Proporção",
    control: "aspectRatio",
    tier: B,
    group: "layout",
    responsive: true,
    default: "4/5",
    options: [
      { value: "auto", label: "Original" },
      { value: "1/1", label: "1:1" },
      { value: "4/5", label: "4:5" },
      { value: "3/2", label: "3:2" },
      { value: "16/9", label: "16:9" },
    ],
  },
  {
    key: "fit",
    label: "Ajuste",
    control: "segmented",
    tier: B,
    group: "layout",
    default: "cover",
    options: [
      { value: "cover", label: "Preencher" },
      { value: "contain", label: "Conter" },
    ],
  },
  {
    key: "focalPoint",
    label: "Ponto de foco",
    control: "focalPoint",
    tier: A,
    group: "layout",
    default: { x: 50, y: 50 },
  },
  {
    key: "overlay",
    label: "Overlay",
    control: "overlay",
    tier: A,
    group: "appearance",
    default: { color: "#000000", opacity: 0 },
  },
  {
    key: "radius",
    label: "Arredondamento",
    control: "radius",
    tier: A,
    group: "appearance",
    default: 8,
    min: 0,
    max: 48,
    unit: "px",
  },
  {
    key: "opacity",
    label: "Opacidade",
    control: "slider",
    tier: A,
    group: "appearance",
    default: 100,
    min: 0,
    max: 100,
    unit: "%",
  },
  {
    key: "visibility",
    label: "Mostrar em",
    control: "visibilityByDevice",
    tier: A,
    group: "responsive",
    default: { desktop: true, tablet: true, mobile: true },
  },
];

export const button: SettingDef[] = [
  { key: "show", label: "Mostrar botão", control: "toggle", tier: B, group: "content", default: true },
  { key: "label", label: "Texto", control: "text", tier: B, group: "content", default: "Saber mais", maxLength: 32 },
  { key: "link", label: "Destino", control: "link", tier: B, group: "content", default: { type: "products" } },
  {
    key: "variant",
    label: "Estilo",
    control: "segmented",
    tier: B,
    group: "appearance",
    default: "solid",
    options: [
      { value: "solid", label: "Sólido" },
      { value: "outline", label: "Contorno" },
      { value: "text", label: "Texto" },
    ],
  },
  {
    key: "size",
    label: "Tamanho",
    control: "segmented",
    tier: B,
    group: "layout",
    responsive: true,
    default: "md",
    options: [
      { value: "sm", label: "P" },
      { value: "md", label: "M" },
      { value: "lg", label: "G" },
    ],
  },
  { key: "bg", label: "Cor de fundo", control: "color", tier: B, group: "appearance", default: "token:buttonBg" },
  {
    key: "textColor",
    label: "Cor do texto",
    control: "color",
    tier: B,
    group: "appearance",
    default: "token:buttonText",
    assist: { contrastWith: "bg" },
  },
  {
    key: "radius",
    label: "Arredondamento",
    control: "radius",
    tier: B,
    group: "appearance",
    default: 8,
    min: 0,
    max: 40,
    unit: "px",
  },
  {
    key: "width",
    label: "Largura",
    control: "segmented",
    tier: A,
    group: "layout",
    responsive: true,
    default: "auto",
    options: [
      { value: "auto", label: "Automática" },
      { value: "full", label: "Total" },
    ],
  },
  {
    key: "weight",
    label: "Peso do texto",
    control: "fontWeight",
    tier: A,
    group: "typography",
    default: 600,
  },
  {
    key: "transform",
    label: "Transformação",
    control: "segmented",
    tier: A,
    group: "typography",
    default: "none",
    options: [
      { value: "none", label: "Normal" },
      { value: "uppercase", label: "MAIÚSC." },
    ],
  },
  { key: "icon", label: "Ícone", control: "icon", tier: A, group: "content", default: "" },
  {
    key: "visibility",
    label: "Mostrar em",
    control: "visibilityByDevice",
    tier: A,
    group: "responsive",
    default: { desktop: true, tablet: true, mobile: true },
  },
];

export const icon: SettingDef[] = [
  { key: "icon", label: "Ícone", control: "icon", tier: B, group: "content", default: "truck" },
  { key: "size", label: "Tamanho", control: "slider", tier: B, group: "layout", default: 28, min: 12, max: 64, unit: "px" },
  { key: "color", label: "Cor", control: "color", tier: B, group: "appearance", default: "token:primary" },
  {
    key: "style",
    label: "Estilo",
    control: "segmented",
    tier: A,
    group: "appearance",
    default: "plain",
    options: [
      { value: "plain", label: "Simples" },
      { value: "circle", label: "Círculo" },
      { value: "square", label: "Quadrado" },
    ],
  },
  { key: "bg", label: "Fundo do ícone", control: "color", tier: A, group: "appearance", default: "token:surfaceAlt" },
  { key: "stroke", label: "Espessura", control: "slider", tier: A, group: "appearance", default: 1.75, min: 1, max: 3, step: 0.25 },
];

export const card: SettingDef[] = [
  { key: "cardBg", label: "Fundo do cartão", control: "color", tier: A, group: "appearance", default: "token:cardBg" },
  { key: "cardRadius", label: "Arredondamento", control: "radius", tier: A, group: "appearance", default: 8, min: 0, max: 40, unit: "px" },
  { key: "cardBorder", label: "Espessura da borda", control: "slider", tier: A, group: "appearance", default: 1, min: 0, max: 6, unit: "px" },
  { key: "cardShadow", label: "Sombra", control: "shadow", tier: A, group: "appearance", default: "sm" },
  { key: "cardPadding", label: "Padding", control: "slider", tier: A, group: "spacing", default: 0, min: 0, max: 48, unit: "px" },
];
