import type { SettingDef, ThemeManifest } from "@/theme-editor/editor/contracts/types";
import * as P from "./presets";

const B = "basic" as const;
const A = "advanced" as const;

const colors: SettingDef[] = [
  { key: "primary", label: "Cor principal", control: "color", tier: B, group: "appearance", default: "#111111" },
  { key: "background", label: "Fundo", control: "color", tier: B, group: "appearance", default: "#FFFFFF" },
  {
    key: "text",
    label: "Texto",
    control: "color",
    tier: B,
    group: "appearance",
    default: "#1A1A1A",
    assist: { contrastWith: "background" },
  },
  { key: "secondary", label: "Cor secundária", control: "color", tier: B, group: "appearance", default: "#8A6F5A" },
  { key: "buttonBg", label: "Fundo dos botões", control: "color", tier: B, group: "appearance", default: "token:primary" },
  {
    key: "buttonText",
    label: "Texto dos botões",
    control: "color",
    tier: B,
    group: "appearance",
    default: "#FFFFFF",
    assist: { contrastWith: "buttonBg" },
  },
  { key: "link", label: "Links", control: "color", tier: A, group: "appearance", default: "token:primary" },
  { key: "price", label: "Preço", control: "color", tier: A, group: "appearance", default: "token:text" },
  { key: "comparePrice", label: "Preço anterior", control: "color", tier: A, group: "appearance", default: "#8C8C8C" },
  { key: "badgeBg", label: "Etiqueta (fundo)", control: "color", tier: A, group: "appearance", default: "#B3261E" },
  { key: "badgeText", label: "Etiqueta (texto)", control: "color", tier: A, group: "appearance", default: "#FFFFFF" },
  { key: "border", label: "Bordas", control: "color", tier: A, group: "appearance", default: "#E5E5E5" },
  { key: "cardBg", label: "Fundo dos cartões", control: "color", tier: A, group: "appearance", default: "#FFFFFF" },
  { key: "surfaceAlt", label: "Fundo secundário", control: "color", tier: A, group: "appearance", default: "#F6F4F0" },
];

const typography: SettingDef[] = [
  { key: "headingFont", label: "Fonte dos títulos", control: "font", tier: B, group: "typography", default: "playfair" },
  { key: "bodyFont", label: "Fonte do texto", control: "font", tier: B, group: "typography", default: "inter" },
  { key: "baseSize", label: "Tamanho geral", control: "slider", tier: B, group: "typography", default: 16, min: 14, max: 20, unit: "px" },
  {
    key: "scale",
    label: "Escala dos títulos",
    control: "segmented",
    tier: B,
    group: "typography",
    default: "normal",
    options: [
      { value: "compact", label: "Compacta" },
      { value: "normal", label: "Normal" },
      { value: "wide", label: "Ampla" },
    ],
  },
  { key: "headingWeight", label: "Peso dos títulos", control: "fontWeight", tier: A, group: "typography", default: 600 },
  { key: "bodyWeight", label: "Peso do texto", control: "fontWeight", tier: A, group: "typography", default: 400 },
  { key: "lineHeightHeading", label: "Altura de linha (títulos)", control: "slider", tier: A, group: "typography", default: 1.15, min: 0.9, max: 1.6, step: 0.05 },
  { key: "lineHeightBody", label: "Altura de linha (corpo)", control: "slider", tier: A, group: "typography", default: 1.6, min: 1.2, max: 2.2, step: 0.05 },
  { key: "letterSpacingHeading", label: "Espaçamento de letras (títulos)", control: "slider", tier: A, group: "typography", default: 0, min: -0.05, max: 0.2, step: 0.01, unit: "em" },
  {
    key: "headingTransform",
    label: "Transformação dos títulos",
    control: "segmented",
    tier: A,
    group: "typography",
    default: "none",
    options: [
      { value: "none", label: "Normal" },
      { value: "uppercase", label: "MAIÚSC." },
      { value: "capitalize", label: "Capitalizar" },
    ],
  },
];

const style: SettingDef[] = [
  { key: "preset", label: "Estilo geral", control: "stylePreset", tier: B, group: "appearance", default: "soft" },
  {
    key: "buttonStyle",
    label: "Estilo dos botões",
    control: "segmented",
    tier: B,
    group: "appearance",
    default: "solid",
    options: [
      { value: "solid", label: "Sólido" },
      { value: "outline", label: "Contorno" },
    ],
  },
  { key: "radius", label: "Arredondamento", control: "radius", tier: B, group: "appearance", default: 8, min: 0, max: 32, unit: "px" },
  {
    key: "cardStyle",
    label: "Estilo dos cartões",
    control: "segmented",
    tier: B,
    group: "appearance",
    default: "border",
    options: [
      { value: "flat", label: "Plano" },
      { value: "border", label: "Com borda" },
      { value: "raised", label: "Elevado" },
    ],
  },
  {
    key: "density",
    label: "Densidade",
    control: "segmented",
    tier: B,
    group: "layout",
    default: "normal",
    options: [
      { value: "compact", label: "Compacta" },
      { value: "normal", label: "Normal" },
      { value: "roomy", label: "Espaçosa" },
    ],
  },
  { key: "borderWidth", label: "Espessura das bordas", control: "slider", tier: A, group: "appearance", default: 1, min: 0, max: 4, unit: "px" },
  { key: "shadowStrength", label: "Sombras", control: "shadow", tier: A, group: "appearance", default: "sm" },
  { key: "imageRadius", label: "Arredondamento das imagens", control: "radius", tier: A, group: "appearance", default: 8, min: 0, max: 32, unit: "px" },
  {
    key: "imageHover",
    label: "Efeito ao passar",
    control: "segmented",
    tier: A,
    group: "behavior",
    default: "zoom",
    options: [
      { value: "none", label: "Nenhum" },
      { value: "zoom", label: "Zoom suave" },
    ],
  },
];

const layout: SettingDef[] = [
  {
    key: "contentWidth",
    label: "Largura do conteúdo",
    control: "segmented",
    tier: B,
    group: "layout",
    default: 1280,
    options: [
      { value: 1100, label: "Estreita" },
      { value: 1280, label: "Normal" },
      { value: 1440, label: "Larga" },
      { value: 0, label: "Total" },
    ],
  },
  { key: "pagePadding", label: "Margens laterais", control: "slider", tier: B, group: "spacing", responsive: true, default: { $r: { desktop: 24, mobile: 16 } }, min: 12, max: 64, unit: "px" },
  {
    key: "sectionSpacing",
    label: "Espaço entre seções",
    control: "sizePreset",
    tier: B,
    group: "spacing",
    responsive: true,
    default: { $r: { desktop: 64, mobile: 40 } },
    min: 0,
    max: 160,
    unit: "px",
    options: [
      { value: 32, label: "Compacto" },
      { value: 64, label: "Normal" },
      { value: 96, label: "Espaçoso" },
    ],
  },
  { key: "gridGap", label: "Espaço entre itens", control: "slider", tier: A, group: "spacing", responsive: true, default: { $r: { desktop: 24, mobile: 12 } }, min: 4, max: 48, unit: "px" },
];

const behavior: SettingDef[] = [
  {
    key: "animations",
    label: "Animações",
    control: "segmented",
    tier: B,
    group: "behavior",
    requires: "animations",
    default: "soft",
    options: [
      { value: "none", label: "Nenhuma" },
      { value: "soft", label: "Suaves" },
      { value: "strong", label: "Marcadas" },
    ],
  },
  { key: "wishlist", label: "Lista de desejos", control: "toggle", tier: B, group: "behavior", requires: "wishlist", default: true },
  { key: "quickView", label: "Vista rápida de produto", control: "toggle", tier: B, group: "behavior", requires: "quickView", default: false },
  { key: "backToTop", label: "Botão voltar ao topo", control: "toggle", tier: A, group: "behavior", default: false },
  { key: "floatingWhatsApp", label: "Botão flutuante de WhatsApp", control: "toggle", tier: B, group: "behavior", requires: "floatingWhatsApp", default: false },
  {
    key: "floatingWhatsAppPos",
    label: "Posição",
    control: "segmented",
    tier: A,
    group: "behavior",
    requires: "floatingWhatsApp",
    visibleWhen: { key: "floatingWhatsApp", truthy: true },
    default: "right",
    options: [
      { value: "left", label: "Esquerda" },
      { value: "right", label: "Direita" },
    ],
  },
  {
    key: "whatsappInfo",
    label: "Número de WhatsApp",
    control: "readonlyInfo",
    tier: B,
    group: "behavior",
    requires: "floatingWhatsApp",
    externalTarget: "store-info",
    default: "O número é gerido em Informações da loja.",
  },
];

const responsive: SettingDef[] = [
  {
    key: "mobileMenuStyle",
    label: "Menu no telemóvel",
    control: "segmented",
    tier: B,
    group: "responsive",
    default: "left",
    options: [
      { value: "left", label: "Esquerda" },
      { value: "right", label: "Direita" },
      { value: "full", label: "Ecrã inteiro" },
    ],
  },
  {
    key: "mobileGridColumns",
    label: "Colunas no telemóvel",
    control: "segmented",
    tier: B,
    group: "responsive",
    default: 2,
    options: [
      { value: 1, label: "1" },
      { value: 2, label: "2" },
    ],
  },
  {
    key: "tabletGridColumns",
    label: "Colunas no tablet",
    control: "segmented",
    tier: A,
    group: "responsive",
    default: 3,
    options: [
      { value: 2, label: "2" },
      { value: 3, label: "3" },
      { value: 4, label: "4" },
    ],
  },
  { key: "mobileFontScale", label: "Escala do texto no telemóvel", control: "slider", tier: A, group: "responsive", default: 100, min: 85, max: 115, unit: "%" },
];

export const demoCommerceManifest: ThemeManifest = {
  schemaVersion: 1,
  id: "demo-commerce",
  name: "Demo Commerce",
  version: "1.0.0",
  rendererId: "demo-commerce",
  capabilities: {
    stickyHeader: true,
    transparentHeader: true,
    wishlist: true,
    quickView: true,
    heroSlides: true,
    announcementRotation: true,
    newsletter: true,
    paymentIcons: true,
    floatingWhatsApp: true,
    animations: true,
    colorSchemes: true,
    cartDrawer: true,
    stickyBuyBarMobile: false,
    whatsappBuy: true,
    variantSwatches: false,
  },
  fonts: [
    { id: "inter", label: "Inter", family: "'Inter', system-ui, sans-serif", weights: [300, 400, 500, 600, 700], category: "sans" },
    { id: "dm-sans", label: "DM Sans", family: "'DM Sans', system-ui, sans-serif", weights: [400, 500, 700], category: "sans" },
    { id: "manrope", label: "Manrope", family: "'Manrope', system-ui, sans-serif", weights: [400, 500, 600, 700, 800], category: "sans" },
    { id: "poppins", label: "Poppins", family: "'Poppins', system-ui, sans-serif", weights: [300, 400, 500, 600, 700], category: "sans" },
    { id: "montserrat", label: "Montserrat", family: "'Montserrat', system-ui, sans-serif", weights: [300, 400, 500, 600, 700], category: "sans" },
    { id: "work-sans", label: "Work Sans", family: "'Work Sans', system-ui, sans-serif", weights: [400, 500, 600, 700], category: "sans" },
    { id: "nunito", label: "Nunito", family: "'Nunito', system-ui, sans-serif", weights: [400, 600, 700], category: "sans" },
    { id: "space-grotesk", label: "Space Grotesk", family: "'Space Grotesk', system-ui, sans-serif", weights: [400, 500, 700], category: "display" },
    { id: "playfair", label: "Playfair Display", family: "'Playfair Display', Georgia, serif", weights: [400, 500, 600, 700], category: "serif" },
    { id: "lora", label: "Lora", family: "'Lora', Georgia, serif", weights: [400, 500, 600, 700], category: "serif" },
    { id: "cormorant", label: "Cormorant Garamond", family: "'Cormorant Garamond', Georgia, serif", weights: [400, 500, 600, 700], category: "serif" },
    { id: "merriweather", label: "Merriweather", family: "'Merriweather', Georgia, serif", weights: [400, 700], category: "serif" },
  ],
  colorSchemes: [
    { id: "light", label: "Claro", colors: { background: "#FFFFFF", text: "#1A1A1A", primary: "#111111", buttonBg: "#111111", buttonText: "#FFFFFF" } },
    { id: "soft", label: "Suave", colors: { background: "#F6F4F0", text: "#1A1A1A", primary: "#8A6F5A", buttonBg: "#8A6F5A", buttonText: "#FFFFFF" } },
    { id: "dark", label: "Escuro", colors: { background: "#161616", text: "#F5F5F5", primary: "#F5F5F5", buttonBg: "#F5F5F5", buttonText: "#161616" } },
  ],
  palettes: [
    { id: "neutral", label: "Neutra", colors: { primary: "#111111", background: "#FFFFFF", text: "#1A1A1A", secondary: "#8A8A8A", buttonBg: "#111111", buttonText: "#FFFFFF", surfaceAlt: "#F5F5F5" } },
    { id: "warm", label: "Quente", colors: { primary: "#8A5A2B", background: "#FFFBF5", text: "#2A1B10", secondary: "#C98A4B", buttonBg: "#8A5A2B", buttonText: "#FFFFFF", surfaceAlt: "#F7EDE1" } },
    { id: "ocean", label: "Oceano", colors: { primary: "#12506B", background: "#FFFFFF", text: "#0F2730", secondary: "#2E90B5", buttonBg: "#12506B", buttonText: "#FFFFFF", surfaceAlt: "#EAF4F8" } },
    { id: "forest", label: "Floresta", colors: { primary: "#1F4D32", background: "#FCFDFB", text: "#15251B", secondary: "#5C8A6A", buttonBg: "#1F4D32", buttonText: "#FFFFFF", surfaceAlt: "#EBF2EC" } },
    { id: "rose", label: "Rosa suave", colors: { primary: "#9B4B63", background: "#FFF9FA", text: "#2E1B21", secondary: "#D98FA4", buttonBg: "#9B4B63", buttonText: "#FFFFFF", surfaceAlt: "#FBECEF" } },
    { id: "night", label: "Noite", colors: { primary: "#E8E8E8", background: "#141414", text: "#F2F2F2", secondary: "#9A9A9A", buttonBg: "#E8E8E8", buttonText: "#141414", surfaceAlt: "#1F1F1F" } },
  ],
  stylePresets: [
    { id: "minimal", label: "Minimal", description: "Linhas retas, sem sombras.", values: { radius: 0, imageRadius: 0, shadowStrength: "none", borderWidth: 1, cardStyle: "flat", buttonStyle: "outline" } },
    { id: "soft", label: "Suave", description: "Cantos arredondados e sombra leve.", values: { radius: 12, imageRadius: 12, shadowStrength: "sm", borderWidth: 1, cardStyle: "border", buttonStyle: "solid" } },
    { id: "strong", label: "Forte", description: "Bordas marcadas e contraste.", values: { radius: 4, imageRadius: 4, shadowStrength: "lg", borderWidth: 2, cardStyle: "raised", buttonStyle: "solid" } },
  ],
  global: [
    { id: "colors", label: "Cores", icon: "palette", settings: colors },
    { id: "typography", label: "Tipografia", icon: "type", settings: typography },
    { id: "style", label: "Estilo", icon: "sparkles", settings: style },
    { id: "layout", label: "Layout", icon: "layout", settings: layout },
    { id: "behavior", label: "Comportamento", icon: "zap", settings: behavior },
    { id: "responsive", label: "Responsividade", icon: "smartphone", settings: responsive },
  ],
  pages: [
    {
      id: "home",
      label: "Início",
      supported: true,
      topSections: ["announcement", "header"],
      sections: [
        { id: "hero", type: "hero" },
        { id: "categories", type: "categories" },
        { id: "products", type: "products" },
        { id: "imageText", type: "imageText" },
        { id: "benefits", type: "benefits" },
      ],
      bottomSections: ["footer"],
    },
    { id: "product", label: "Produto", supported: false, previewNeeds: "product", topSections: ["announcement", "header"], sections: [], bottomSections: ["footer"] },
    { id: "collection", label: "Coleção", supported: false, topSections: [], sections: [], bottomSections: [] },
    { id: "cart", label: "Carrinho", supported: false, topSections: [], sections: [], bottomSections: [] },
  ],
  blockTypes: [
    {
      type: "announcementMessage",
      label: "Mensagem",
      icon: "megaphone",
      labelKey: "message",
      elements: [
        {
          id: "message",
          kind: "text",
          label: "Mensagem",
          settings: {
            preset: "text",
            omit: ["maxLines", "opacity", "marginBottom", "align"],
            override: { text: { default: "Entrega grátis em compras acima de 50 €" }, size: { default: 13 }, color: { default: "#FFFFFF" } },
          },
        },
      ],
    },
    {
      type: "heroSlide",
      label: "Slide",
      icon: "image",
      labelKey: "title",
      elements: [
        {
          id: "image",
          kind: "image",
          label: "Imagem",
          settings: { preset: "image", override: { aspectRatio: { default: "auto" }, image: { assist: { recommended: { width: 1920, height: 900 } } } } },
        },
        { id: "eyebrow", kind: "text", label: "Sobretítulo", settings: { preset: "text", override: { text: { default: "Nova coleção" }, show: { default: false }, size: { default: 14 }, color: { default: "#FFFFFF" } } } },
        { id: "title", kind: "heading", label: "Título", settings: { preset: "heading", override: { text: { default: "Descubra o que combina com você" }, htmlTag: { default: "h1" }, size: { default: { $r: { desktop: 48, mobile: 34 } } }, color: { default: "#FFFFFF" } } } },
        { id: "description", kind: "text", label: "Descrição", settings: { preset: "text", override: { text: { default: "Uma seleção de peças pensadas para o seu dia a dia." }, color: { default: "#FFFFFF" } } } },
        { id: "button1", kind: "button", label: "Botão principal", settings: { preset: "button", override: { label: { default: "Explorar produtos" } } } },
        { id: "button2", kind: "button", label: "Botão secundário", settings: { preset: "button", override: { label: { default: "Ver categorias" }, show: { default: false }, variant: { default: "outline" } } } },
      ],
    },
    {
      type: "benefit",
      label: "Benefício",
      icon: "badge-check",
      labelKey: "title",
      elements: [
        { id: "icon", kind: "icon", label: "Ícone", settings: { preset: "icon" } },
        { id: "title", kind: "heading", label: "Título", settings: { preset: "heading", override: { text: { default: "Entrega rápida" }, htmlTag: { default: "h3" }, size: { default: 18 } } } },
        { id: "description", kind: "text", label: "Descrição", settings: { preset: "text", override: { text: { default: "Enviamos em 24 horas úteis." }, size: { default: 14 } } } },
      ],
    },
    {
      type: "faqItem",
      label: "Pergunta",
      icon: "circle-help",
      labelKey: "question",
      elements: [
        { id: "question", kind: "heading", label: "Pergunta", settings: { preset: "heading", omit: ["htmlTag"], override: { text: { default: "Qual é o prazo de entrega?" }, size: { default: 18 } } } },
        { id: "answer", kind: "text", label: "Resposta", settings: { preset: "text", override: { text: { default: "Entre 3 e 5 dias úteis para todo o país." } } } },
      ],
    },
    {
      type: "footerColumn",
      label: "Coluna",
      icon: "columns-3",
      labelKey: "title",
      elements: [
        { id: "title", kind: "heading", label: "Título", settings: { preset: "heading", override: { text: { default: "Loja" }, size: { default: 16 }, color: { default: "#FFFFFF" } } } },
        {
          id: "menu",
          kind: "menu",
          label: "Menu",
          settings: [
            { key: "menuId", label: "Menu", control: "select", tier: "basic", group: "content", default: "main", options: [{ value: "main", label: "Menu principal" }, { value: "help", label: "Ajuda" }] },
            { key: "menuInfo", label: "Links", control: "readonlyInfo", tier: "basic", group: "content", externalTarget: "navigation-menus", default: "Os links são geridos em Menus." },
            { key: "size", label: "Tamanho do texto", control: "slider", tier: "advanced", group: "typography", default: 14, min: 11, max: 20, unit: "px" },
            { key: "color", label: "Cor", control: "color", tier: "advanced", group: "appearance", default: "#D8D8D8" },
          ],
        },
      ],
    },
  ],
  presets: {
    container: P.container,
    heading: P.heading,
    text: P.text,
    image: P.image,
    button: P.button,
    icon: P.icon,
    card: P.card,
  },
  icons: [
    "truck", "shield-check", "message-circle", "credit-card", "gift", "heart", "star",
    "package", "refresh-cw", "clock", "phone", "mail", "map-pin", "sparkles", "leaf",
    "percent", "tag", "shopping-bag", "headphones", "award",
  ],
  sectionTypes: [
    {
      type: "announcement",
      label: "Barra de anúncio",
      description: "Mensagem fina no topo da loja.",
      icon: "megaphone",
      scope: "global",
      required: false,
      removable: true,
      duplicable: false,
      reorderable: false,
      hideable: true,
      maxInstances: 1,
      elements: [],
      blocks: { allowed: ["announcementMessage"], min: 1, max: 5, itemLabel: "Mensagem", itemLabelPlural: "Mensagens", addLabel: "Adicionar mensagem", defaultCount: 1 },
      settings: {
        preset: "container",
        omit: ["spacing", "contentWidth", "minHeight", "radius", "shadow", "gap"],
        override: { colorScheme: { default: "dark" } },
        add: [
          { key: "height", label: "Altura", control: "slider", tier: B, group: "layout", responsive: true, default: 40, min: 28, max: 64, unit: "px" },
          { key: "autoRotate", label: "Rodar mensagens", control: "toggle", tier: B, group: "behavior", requires: "announcementRotation", visibleWhen: { key: "$blockCount", gt: 1 }, default: true },
          { key: "interval", label: "Intervalo", control: "slider", tier: A, group: "behavior", visibleWhen: { key: "$blockCount", gt: 1 }, default: 5, min: 3, max: 10, unit: "s" },
          { key: "dismissible", label: "Permitir fechar", control: "toggle", tier: A, group: "behavior", default: false },
        ],
      },
    },
    {
      type: "header",
      label: "Cabeçalho",
      description: "Logótipo, menu e ícones.",
      icon: "panel-top",
      scope: "global",
      required: true,
      removable: false,
      duplicable: false,
      reorderable: false,
      hideable: false,
      elements: [
        {
          id: "logo",
          kind: "logo",
          label: "Logótipo",
          settings: {
            preset: "image",
            omit: ["aspectRatio", "fit", "focalPoint", "overlay", "opacity"],
            add: [{ key: "width", label: "Largura", control: "slider", tier: B, group: "layout", responsive: true, default: { $r: { desktop: 120, mobile: 90 } }, min: 40, max: 240, unit: "px" }],
          },
        },
        {
          id: "menu",
          kind: "menu",
          label: "Menu",
          settings: [
            { key: "menuInfo", label: "Links do menu", control: "readonlyInfo", tier: B, group: "content", externalTarget: "navigation-menus", default: "Os links são geridos em Menus." },
            { key: "size", label: "Tamanho", control: "slider", tier: B, group: "typography", default: 15, min: 12, max: 20, unit: "px" },
            { key: "weight", label: "Peso", control: "fontWeight", tier: A, group: "typography", default: 500 },
            { key: "spacing", label: "Espaço entre links", control: "slider", tier: A, group: "spacing", default: 24, min: 8, max: 48, unit: "px" },
            { key: "transform", label: "Transformação", control: "segmented", tier: A, group: "typography", default: "none", options: [{ value: "none", label: "Normal" }, { value: "uppercase", label: "MAIÚSC." }] },
            { key: "color", label: "Cor", control: "color", tier: A, group: "appearance", default: "token:text" },
          ],
        },
        {
          id: "icons",
          kind: "icon",
          label: "Ícones",
          settings: [
            { key: "iconSize", label: "Tamanho dos ícones", control: "slider", tier: B, group: "layout", default: 20, min: 16, max: 32, unit: "px" },
            { key: "showCount", label: "Contador do carrinho", control: "toggle", tier: B, group: "behavior", default: true },
            { key: "color", label: "Cor", control: "color", tier: A, group: "appearance", default: "token:text" },
          ],
        },
      ],
      settings: {
        preset: "container",
        omit: ["spacing", "align", "minHeight", "radius", "shadow", "gap", "animation"],
        add: [
          {
            key: "layout",
            label: "Disposição",
            control: "segmented",
            tier: B,
            group: "layout",
            default: "logoLeft",
            options: [
              { value: "logoLeft", label: "Logo à esquerda" },
              { value: "logoCenter", label: "Logo ao centro" },
              { value: "menuBelow", label: "Menu por baixo" },
            ],
          },
          { key: "showStoreName", label: "Mostrar nome da loja", control: "toggle", tier: B, group: "content", default: false },
          { key: "showSearch", label: "Mostrar pesquisa", control: "toggle", tier: B, group: "content", default: true },
          { key: "showAccount", label: "Mostrar conta", control: "toggle", tier: B, group: "content", default: true },
          { key: "showCart", label: "Mostrar carrinho", control: "toggle", tier: B, group: "content", default: true },
          { key: "showWishlist", label: "Mostrar favoritos", control: "toggle", tier: B, group: "content", requires: "wishlist", default: false },
          {
            key: "sticky",
            label: "Cabeçalho fixo",
            control: "segmented",
            tier: B,
            group: "behavior",
            requires: "stickyHeader",
            default: "never",
            options: [
              { value: "never", label: "Nunca" },
              { value: "always", label: "Sempre" },
              { value: "onScrollUp", label: "Ao subir" },
            ],
          },
          { key: "height", label: "Altura", control: "slider", tier: A, group: "layout", responsive: true, default: { $r: { desktop: 72, mobile: 56 } }, min: 48, max: 120, unit: "px" },
          { key: "borderBottom", label: "Linha inferior", control: "toggle", tier: A, group: "appearance", default: true },
        ],
      },
    },
    {
      type: "hero",
      label: "Banner principal",
      description: "Imagem grande com título e botão.",
      icon: "image",
      scope: "page",
      allowedPages: ["home"],
      required: true,
      removable: false,
      duplicable: false,
      reorderable: true,
      hideable: true,
      elements: [],
      blocks: { allowed: ["heroSlide"], min: 1, max: 5, itemLabel: "Slide", itemLabelPlural: "Slides", addLabel: "Adicionar slide", defaultCount: 1 },
      settings: {
        preset: "container",
        omit: ["spacing", "gap", "colorScheme", "align"],
        override: { padding: { default: { $r: { desktop: 48, mobile: 24 } } } },
        add: [
          { key: "height", label: "Altura", control: "slider", tier: B, group: "layout", responsive: true, default: { $r: { desktop: 520, tablet: 420, mobile: 360 } }, min: 240, max: 900, unit: "px" },
          { key: "hAlign", label: "Alinhamento horizontal", control: "align", tier: B, group: "layout", responsive: true, default: "left" },
          { key: "vAlign", label: "Alinhamento vertical", control: "alignV", tier: B, group: "layout", responsive: true, default: "center" },
          { key: "overlay", label: "Escurecer imagem", control: "overlay", tier: B, group: "appearance", default: { color: "#000000", opacity: 25 } },
          { key: "autoplay", label: "Rodar automaticamente", control: "toggle", tier: B, group: "behavior", visibleWhen: { key: "$blockCount", gt: 1 }, default: true },
          { key: "showDots", label: "Mostrar pontos", control: "toggle", tier: B, group: "behavior", visibleWhen: { key: "$blockCount", gt: 1 }, default: true },
        ],
      },
    },
    {
      type: "categories",
      label: "Categorias",
      description: "Grelha ou carrossel de categorias.",
      icon: "grid-3x3",
      scope: "page",
      allowedPages: ["home"],
      required: false,
      removable: true,
      duplicable: true,
      reorderable: true,
      hideable: true,
      maxInstances: 2,
      dataSource: { kind: "categories", modes: ["all", "manual"], maxItems: { min: 2, max: 12 } },
      elements: [
        { id: "title", kind: "heading", label: "Título", settings: { preset: "heading", override: { text: { default: "Compre por categoria" } } } },
        { id: "subtitle", kind: "text", label: "Subtítulo", settings: { preset: "text", override: { text: { default: "Escolha por estilo." }, show: { default: false } } } },
        { id: "viewAll", kind: "button", label: "Botão ver todas", settings: { preset: "button", override: { label: { default: "Ver todas" }, variant: { default: "text" } } } },
        {
          id: "itemLabel",
          kind: "text",
          label: "Nome da categoria",
          settings: { preset: "text", omit: ["text", "maxLines"], override: { size: { default: 15 }, weight: { default: 600 } } },
        },
      ],
      settings: {
        preset: "container",
        add: [
          { key: "layout", label: "Disposição", control: "segmented", tier: B, group: "layout", default: "grid", options: [{ value: "grid", label: "Grelha" }, { value: "carousel", label: "Carrossel" }, { value: "list", label: "Lista" }] },
          { key: "source", label: "Origem", control: "segmented", tier: B, group: "content", default: "all", options: [{ value: "all", label: "Todas" }, { value: "manual", label: "Seleção manual" }] },
          { key: "picked", label: "Categorias", control: "categoryPicker", tier: B, group: "content", visibleWhen: { key: "source", equals: "manual" }, default: [] },
          { key: "maxItems", label: "Quantidade", control: "number", tier: B, group: "content", default: 6, min: 2, max: 12 },
          { key: "columns", label: "Colunas", control: "number", tier: B, group: "layout", responsive: true, default: { $r: { desktop: 4, tablet: 3, mobile: 2 } }, min: 1, max: 6 },
          { key: "titlePlacement", label: "Nome da categoria", control: "segmented", tier: B, group: "layout", default: "below", options: [{ value: "over", label: "Sobre a imagem" }, { value: "below", label: "Abaixo" }, { value: "hidden", label: "Oculto" }] },
          { key: "showCount", label: "Mostrar nº de produtos", control: "toggle", tier: A, group: "content", default: false },
          { key: "categoriesInfo", label: "Categorias", control: "readonlyInfo", tier: B, group: "content", externalTarget: "categories", default: "As categorias são geridas em Categorias." },
        ],
      },
    },
    {
      type: "products",
      label: "Produtos",
      description: "Grelha de produtos da loja.",
      icon: "shopping-bag",
      scope: "page",
      allowedPages: ["home"],
      required: false,
      removable: true,
      duplicable: true,
      reorderable: true,
      hideable: true,
      maxInstances: 3,
      dataSource: { kind: "products", modes: ["all", "category", "manual"], sort: ["recent", "best", "priceAsc", "priceDesc"], maxItems: { min: 2, max: 24 } },
      elements: [
        { id: "title", kind: "heading", label: "Título", settings: { preset: "heading", override: { text: { default: "Produtos em destaque" } } } },
        { id: "subtitle", kind: "text", label: "Subtítulo", settings: { preset: "text", override: { text: { default: "Seleção da semana." }, show: { default: false } } } },
        { id: "viewAll", kind: "button", label: "Botão ver todos", settings: { preset: "button", override: { label: { default: "Ver todos" }, variant: { default: "text" } } } },
        {
          id: "productCard",
          kind: "productCard",
          label: "Cartão de produto",
          settings: [
            { key: "showImage", label: "Mostrar imagem", control: "toggle", tier: B, group: "content", default: true },
            { key: "showName", label: "Mostrar nome", control: "toggle", tier: B, group: "content", default: true },
            { key: "showPrice", label: "Mostrar preço", control: "toggle", tier: B, group: "content", default: true },
            { key: "showComparePrice", label: "Mostrar preço anterior", control: "toggle", tier: B, group: "content", default: true },
            { key: "showBadge", label: "Mostrar etiqueta", control: "toggle", tier: B, group: "content", default: true },
            { key: "showWishlist", label: "Mostrar favorito", control: "toggle", tier: B, group: "content", requires: "wishlist", default: true },
            { key: "showAddToCart", label: "Botão adicionar", control: "toggle", tier: B, group: "content", default: false },
            { key: "aspectRatio", label: "Proporção da imagem", control: "aspectRatio", tier: A, group: "layout", responsive: true, default: "4/5", options: [{ value: "1/1", label: "1:1" }, { value: "4/5", label: "4:5" }, { value: "3/4", label: "3:4" }] },
            { key: "align", label: "Alinhamento", control: "align", tier: A, group: "layout", default: "left" },
            { key: "nameLines", label: "Linhas do nome", control: "select", tier: A, group: "layout", default: 2, options: [{ value: 1, label: "1" }, { value: 2, label: "2" }, { value: 3, label: "3" }, { value: 0, label: "Sem limite" }] },
            { key: "nameSize", label: "Tamanho do nome", control: "slider", tier: A, group: "typography", default: 15, min: 11, max: 24, unit: "px" },
            { key: "priceSize", label: "Tamanho do preço", control: "slider", tier: A, group: "typography", default: 16, min: 12, max: 32, unit: "px" },
            { key: "priceColor", label: "Cor do preço", control: "color", tier: A, group: "appearance", default: "token:price" },
            { key: "textGap", label: "Espaço entre textos", control: "slider", tier: A, group: "spacing", default: 6, min: 0, max: 24, unit: "px" },
            ...P.card,
            { key: "productsInfo", label: "Produtos", control: "readonlyInfo", tier: B, group: "content", externalTarget: "products", default: "Nome, preço e imagem são geridos em Produtos." },
          ],
        },
      ],
      settings: {
        preset: "container",
        add: [
          { key: "mode", label: "Origem", control: "segmented", tier: B, group: "content", default: "all", options: [{ value: "all", label: "Todos" }, { value: "category", label: "Categoria" }, { value: "manual", label: "Manual" }] },
          { key: "category", label: "Categoria", control: "select", tier: B, group: "content", visibleWhen: { key: "mode", equals: "category" }, default: "c1", options: [] },
          { key: "picked", label: "Produtos", control: "productPicker", tier: B, group: "content", visibleWhen: { key: "mode", equals: "manual" }, default: [] },
          { key: "count", label: "Quantidade", control: "number", tier: B, group: "content", default: 8, min: 2, max: 24 },
          { key: "sort", label: "Ordenar por", control: "select", tier: B, group: "content", default: "recent", options: [{ value: "recent", label: "Mais recentes" }, { value: "best", label: "Mais vendidos" }, { value: "priceAsc", label: "Preço ↑" }, { value: "priceDesc", label: "Preço ↓" }] },
          { key: "layout", label: "Disposição", control: "segmented", tier: B, group: "layout", default: "grid", options: [{ value: "grid", label: "Grelha" }, { value: "carousel", label: "Carrossel" }] },
          { key: "columns", label: "Colunas", control: "number", tier: B, group: "layout", responsive: true, default: { $r: { desktop: 4, tablet: 3, mobile: 2 } }, min: 1, max: 6 },
        ],
      },
    },
    {
      type: "imageText",
      label: "Imagem + texto",
      description: "Uma imagem ao lado de um texto.",
      icon: "panels-top-left",
      scope: "page",
      allowedPages: ["home"],
      required: false,
      removable: true,
      duplicable: true,
      reorderable: true,
      hideable: true,
      maxInstances: 4,
      elements: [
        { id: "image", kind: "image", label: "Imagem", settings: { preset: "image", override: { aspectRatio: { default: "1/1" } } } },
        { id: "eyebrow", kind: "text", label: "Sobretítulo", settings: { preset: "text", override: { text: { default: "Sobre nós" }, show: { default: false }, size: { default: 14 } } } },
        { id: "title", kind: "heading", label: "Título", settings: { preset: "heading", override: { text: { default: "Feito para durar" } } } },
        { id: "description", kind: "text", label: "Descrição", settings: { preset: "text", override: { text: { default: "Materiais escolhidos com cuidado e acabamentos pensados ao detalhe." } } } },
        { id: "button", kind: "button", label: "Botão", settings: { preset: "button", override: { label: { default: "Saber mais" }, variant: { default: "outline" } } } },
      ],
      settings: {
        preset: "container",
        add: [
          { key: "imagePosition", label: "Posição da imagem", control: "segmented", tier: B, group: "layout", responsive: true, default: "left", options: [{ value: "left", label: "Esquerda" }, { value: "right", label: "Direita" }] },
          { key: "imageWidth", label: "Largura da imagem", control: "segmented", tier: B, group: "layout", responsive: true, default: 50, options: [{ value: 40, label: "40%" }, { value: 50, label: "50%" }, { value: 60, label: "60%" }] },
          { key: "vAlign", label: "Alinhamento vertical", control: "alignV", tier: B, group: "layout", default: "center" },
          { key: "mobileOrder", label: "No telemóvel", control: "segmented", tier: B, group: "responsive", default: "image", options: [{ value: "image", label: "Imagem primeiro" }, { value: "textFirst", label: "Texto primeiro" }] },
        ],
      },
    },
    {
      type: "benefits",
      label: "Benefícios",
      description: "Ícones com vantagens da loja.",
      icon: "badge-check",
      scope: "page",
      allowedPages: ["home"],
      required: false,
      removable: true,
      duplicable: true,
      reorderable: true,
      hideable: true,
      maxInstances: 2,
      elements: [
        { id: "title", kind: "heading", label: "Título", settings: { preset: "heading", override: { text: { default: "Porquê comprar aqui" }, show: { default: false } } } },
      ],
      blocks: { allowed: ["benefit"], min: 2, max: 6, itemLabel: "Benefício", itemLabelPlural: "Benefícios", addLabel: "Adicionar benefício", defaultCount: 3 },
      settings: {
        preset: "container",
        add: [
          { key: "layout", label: "Disposição", control: "segmented", tier: B, group: "layout", default: "row", options: [{ value: "row", label: "Linha" }, { value: "grid", label: "Grelha" }, { value: "list", label: "Lista" }] },
          { key: "columns", label: "Colunas", control: "number", tier: B, group: "layout", responsive: true, default: { $r: { desktop: 3, tablet: 3, mobile: 1 } }, min: 1, max: 6 },
          { key: "itemStyle", label: "Estilo dos itens", control: "segmented", tier: A, group: "appearance", default: "plain", options: [{ value: "plain", label: "Sem caixa" }, { value: "border", label: "Com borda" }, { value: "filled", label: "Preenchido" }] },
        ],
      },
    },
    {
      type: "richText",
      label: "Texto",
      description: "Um bloco de texto simples.",
      icon: "text",
      scope: "page",
      allowedPages: ["home"],
      required: false,
      removable: true,
      duplicable: true,
      reorderable: true,
      hideable: true,
      maxInstances: 5,
      elements: [
        { id: "title", kind: "heading", label: "Título", settings: { preset: "heading", override: { text: { default: "A nossa história" }, align: { default: "center" } } } },
        { id: "text", kind: "text", label: "Texto", settings: { preset: "text", override: { text: { default: "Começámos numa pequena oficina e hoje enviamos para todo o país." }, align: { default: "center" } } } },
        { id: "button", kind: "button", label: "Botão", settings: { preset: "button", override: { show: { default: false } } } },
      ],
      settings: {
        preset: "container",
        override: { align: { default: "center" }, contentWidth: { default: "narrow" } },
      },
    },
    {
      type: "faq",
      label: "Perguntas frequentes",
      description: "Lista de perguntas e respostas.",
      icon: "circle-help",
      scope: "page",
      allowedPages: ["home"],
      required: false,
      removable: true,
      duplicable: false,
      reorderable: true,
      hideable: true,
      maxInstances: 2,
      elements: [
        { id: "title", kind: "heading", label: "Título", settings: { preset: "heading", override: { text: { default: "Perguntas frequentes" }, align: { default: "center" } } } },
      ],
      blocks: { allowed: ["faqItem"], min: 1, max: 12, itemLabel: "Pergunta", itemLabelPlural: "Perguntas", addLabel: "Adicionar pergunta", defaultCount: 3 },
      settings: {
        preset: "container",
        override: { contentWidth: { default: "narrow" } },
        add: [
          { key: "style", label: "Estilo", control: "segmented", tier: B, group: "layout", default: "accordion", options: [{ value: "accordion", label: "Acordeão" }, { value: "open", label: "Lista aberta" }] },
          { key: "firstOpen", label: "Primeira aberta", control: "toggle", tier: B, group: "behavior", default: true },
        ],
      },
    },
    {
      type: "promoBanner",
      label: "Banner promocional",
      description: "Faixa com imagem, texto e botão.",
      icon: "percent",
      scope: "page",
      allowedPages: ["home"],
      required: false,
      removable: true,
      duplicable: true,
      reorderable: true,
      hideable: true,
      maxInstances: 3,
      elements: [
        { id: "image", kind: "image", label: "Imagem de fundo", settings: { preset: "image", override: { aspectRatio: { default: "auto" } } } },
        { id: "title", kind: "heading", label: "Título", settings: { preset: "heading", override: { text: { default: "-20% esta semana" }, color: { default: "#FFFFFF" } } } },
        { id: "description", kind: "text", label: "Descrição", settings: { preset: "text", override: { text: { default: "Só até domingo, em artigos selecionados." }, color: { default: "#FFFFFF" } } } },
        { id: "button", kind: "button", label: "Botão", settings: { preset: "button", override: { label: { default: "Aproveitar" } } } },
      ],
      settings: {
        preset: "container",
        omit: ["colorScheme", "align"],
        add: [
          { key: "height", label: "Altura", control: "slider", tier: B, group: "layout", responsive: true, default: 320, min: 160, max: 600, unit: "px" },
          { key: "hAlign", label: "Alinhamento horizontal", control: "align", tier: B, group: "layout", default: "center" },
          { key: "vAlign", label: "Alinhamento vertical", control: "alignV", tier: B, group: "layout", default: "center" },
          { key: "overlay", label: "Escurecer imagem", control: "overlay", tier: B, group: "appearance", default: { color: "#000000", opacity: 35 } },
        ],
      },
    },
    {
      type: "footer",
      label: "Rodapé",
      description: "Colunas, redes sociais e contactos.",
      icon: "panel-bottom",
      scope: "global",
      required: true,
      removable: false,
      duplicable: false,
      reorderable: false,
      hideable: false,
      elements: [
        { id: "description", kind: "text", label: "Descrição da loja", settings: { preset: "text", omit: ["text"], override: { color: { default: "#C9C9C9" }, size: { default: 14 } } } },
        {
          id: "socialLinks",
          kind: "socialLinks",
          label: "Redes sociais",
          settings: [
            { key: "instagram", label: "Instagram", control: "toggle", tier: B, group: "content", default: true },
            { key: "facebook", label: "Facebook", control: "toggle", tier: B, group: "content", default: true },
            { key: "tiktok", label: "TikTok", control: "toggle", tier: B, group: "content", default: false },
            { key: "whatsapp", label: "WhatsApp", control: "toggle", tier: B, group: "content", default: true },
            { key: "youtube", label: "YouTube", control: "toggle", tier: B, group: "content", default: false },
            { key: "size", label: "Tamanho", control: "slider", tier: B, group: "layout", default: 20, min: 16, max: 40, unit: "px" },
            { key: "style", label: "Estilo", control: "segmented", tier: A, group: "appearance", default: "plain", options: [{ value: "plain", label: "Simples" }, { value: "circle", label: "Círculo" }, { value: "square", label: "Quadrado" }] },
            { key: "color", label: "Cor", control: "color", tier: A, group: "appearance", default: "#FFFFFF" },
            { key: "socialInfo", label: "Endereços", control: "readonlyInfo", tier: B, group: "content", externalTarget: "social-links", default: "Os endereços são geridos em Redes sociais." },
          ],
        },
        {
          id: "policyLinks",
          kind: "policyLinks",
          label: "Políticas",
          settings: [
            { key: "returns", label: "Devoluções", control: "toggle", tier: B, group: "content", default: true },
            { key: "privacy", label: "Privacidade", control: "toggle", tier: B, group: "content", default: true },
            { key: "terms", label: "Termos", control: "toggle", tier: B, group: "content", default: true },
            { key: "shipping", label: "Envio", control: "toggle", tier: B, group: "content", default: false },
            { key: "policiesInfo", label: "Conteúdo", control: "readonlyInfo", tier: B, group: "content", externalTarget: "policies", default: "O conteúdo é gerido em Páginas e políticas." },
          ],
        },
        {
          id: "contacts",
          kind: "text",
          label: "Contactos",
          settings: [
            { key: "email", label: "Mostrar e-mail", control: "toggle", tier: B, group: "content", default: true },
            { key: "phone", label: "Mostrar telefone", control: "toggle", tier: B, group: "content", default: true },
            { key: "address", label: "Mostrar morada", control: "toggle", tier: B, group: "content", default: false },
            { key: "hours", label: "Mostrar horário", control: "toggle", tier: B, group: "content", default: false },
            { key: "storeInfo", label: "Dados", control: "readonlyInfo", tier: B, group: "content", externalTarget: "store-info", default: "Os dados são geridos em Informações da loja." },
          ],
        },
        {
          id: "newsletter",
          kind: "input",
          label: "Newsletter",
          settings: [
            { key: "show", label: "Mostrar newsletter", control: "toggle", tier: B, group: "content", requires: "newsletter", default: true },
            { key: "title", label: "Título", control: "text", tier: B, group: "content", default: "Receba novidades", maxLength: 60 },
            { key: "placeholder", label: "Texto do campo", control: "text", tier: B, group: "content", default: "O seu e-mail", maxLength: 40 },
            { key: "submitLabel", label: "Texto do botão", control: "text", tier: B, group: "content", default: "Subscrever", maxLength: 24 },
          ],
        },
        {
          id: "copyright",
          kind: "text",
          label: "Direitos de autor",
          settings: { preset: "text", override: { text: { default: "© {ano} {loja}. Todos os direitos reservados.", maxLength: 120 }, size: { default: 13 }, color: { default: "#A3A3A3" }, align: { default: "center" } } },
        },
      ],
      blocks: { allowed: ["footerColumn"], min: 1, max: 4, itemLabel: "Coluna", itemLabelPlural: "Colunas", addLabel: "Adicionar coluna", defaultCount: 3 },
      settings: {
        preset: "container",
        omit: ["minHeight", "radius", "animation"],
        override: { colorScheme: { default: "dark" }, spacing: { default: 48 } },
        add: [
          { key: "borderTop", label: "Linha superior", control: "toggle", tier: A, group: "appearance", default: false },
          { key: "bottomBar", label: "Barra inferior", control: "toggle", tier: A, group: "layout", default: true },
        ],
      },
    },
  ],
};
