name: Copia para GitLab
on:
  push:
    branches:
      - main
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enviar para GitLab
        run: |
          git remote add gitlab https://oauth2:${{glpat--SDg0U9KHPKeXaAhfUCYHmM6MQpvOjEKdTpwbzJmbQ8.01.170886s8i}}@gitlab.com/joseluiscunha18/shopyump-dashboard.git
          git push gitlab main --force
